/*
* Facultad de Estudios Tecnológicos
* Lenguajes Interpretados en el Cliente
* Fichero: ventas.js
* Uso: Obtener el bono por ventas anuales de n empleados
* Ciclo 2-2014
*<>
*/
var i;
var problema=new Array();
problema.push("<h2>1) EL MOUSE NO RESPONDE  <br></h2><h1>Si no aparece el Mouse en la pantalla o tiene problemas de desplazamiento, ve a inicio / configuracion / panel de control / mouse. Los indicadores que aparecen a lo largo de la ventana del Mouse te permitiran controlar las funciones del Mouse. Si la configuracion esta correcta, verifica que el Mouse este conectado correctamente. Tambien puedes abrir el Mouse y limpiarlo con un copito de algodon y alcohol. <br>Muchas de las fallas que encuentras, las puedes solucionar, si no debes acudir a un profesional. No pierdas la esperanza de solucionar tus problemas. Tambien los vendedores de computadoras y equipos perifericos te pueden suministrar asistencia tecnica directa o te pueden recomendar centros especializados de reparacion de computadoras. </h1>");
problema.push("<h2>2) MI COMPUTADORA ES DEMASIADO LENTA<br></h2><h1>El primer paso para arreglar un equipo lento es verificar que el equipo en si sea la verdadera fuente del problema. Los videos y sitios web parecen tardan años en cargar, entonces puede ser que la culpa no sea de tu computadora. El agente de Geek Squad, Derek Meister, dice que mucha gente identifica erroneamente a un sistema como lento cuando el problema - en realidad no es la computadora, sino su conexion de banda ancha - . Sigue leyendo para obtener instrucciones sobre como utilizar Speedtest.net para diagnosticar una conexion lenta.<br> Si el problema si es tu PC, verifica si aun tienes espacio libre en el disco duro y en tu sistema operativo. Windows necesita espacio para crear archivos mientras el sistema esta funcionando. Si el disco duro esta al limite, obviamente el rendimiento tendra problemas. Ahora es el momento perfecto para librarte de un poco de espacio.<br> La herramienta de Configuracion del Sistema de Microsoft es su apuesta mas para afrontar la lentitud. Muchas aplicaciones inician automaticamente cuando la maquina arranca, esto puede alargar el tiempo de arranque, especialmente en PCs mas viejas, haciendolas tambien mas lentas. Haz el habito de recortar los elementos de inicio. Abre la herramienta de Microsoft presionando Windows-R, y escribe msconfig y da aceptar o enter.<br>Checa las columnas de Iconos de Inicio y Fabricante ya que es la mejor manera de averiguar quienes son los asesinos potenciales que toman el rendimiento de tu PC y que con seguridad puedes deshabilitar.<br> Evita jugar con cualquiera de los servicios y programas que tenga Microsoft Corporation marcado como fabricante. Articulos tales como AdobeAAMUpdater, Google Update, Pando Media Booster, Spotify y Stream Client Bootstrapper pueden entrar en esta lista. A pesar de todo, debes ser cauteloso: Si no estas seguro de lo que hace un programa o servicio, no lo desactives.<br> Una vez que has hecho todos los cambios, haz clic en aceptar y reinicia el equipo. Debe arrancar mas rapido y sentirlo notablemente mas rapido en terminos generales.</h1>");
problema.push("<h2>3) LAS DESCARGAS ESTAN TARDANDO DEMASIADO<br></h2><h1>Speedtest.net es tu mejor amigo cuando estas teniendo problemas de conectividad. Ejecuta una prueba de velocidad para ver cuanta es la velocidad de descarga y subida, idealmente deberian ser por lo menos el 50 por ciento de la velocidad que anuncia tu proveedor de Internet, con un ping bajo 100 milisegundos.<br>Si las velocidades parecen solidas, asegurate de que no estes inadvertidamente descargando o cargando algo. Muchos programas de descargas trabajan de fondo y minimizan la capacidad de la bandeja del sistema en vez de la barra de tareas. <br>Comprueba el hardware de red. Las actualizaciones para las tarjetas de red no son tan comunes, pero si el fabricante de tu tarjeta ofrece un nuevo driver, descargarlo. Reiniciar tu router y modem puede ayudar con problemas de conexion tambien. La mayoria de routers y modems tienen botones de reinicio, pero jalando el cable de alimentacion durante un par de segundos puede hacer lo mismo. No cortes la alimentacion de energia por mucho tiempo, o el hardware puede restablecerse con los valores de fabrica predeterminados.<br> ¿ Sigues teniendo problemas? Llama a tu ISP, ellos te pueden decir si el problema que presentas es mas extremo. Como ultima medida, el ISP podria restablecer la conexion principal de tu hogar.</h1>");
problema.push("<h2>4) MI EQUIPO SE REINICIA <br></h2><h1>Son dificiles de diagnosticar y solucionar problemas de hardware. En primer lugar, confirma que simplemente no son problemas ocasionados por las actualizaciones automaticas de Windows, que pueden reiniciar automaticamente el equipo despues de la instalacion. Entonces checa que se encuentren actualizados todos los controladores criticos del sistema. Tu tarjeta grafica, tarjeta madre y los controladores de la tarjeta de red son cruciales.<br>- A veces puede ser virus, a veces puede ser un adware, a veces puede ser sobrecalentamiento, y a veces puede ser algo tan simple como una actualizacion de la tarjeta de video,-  afirma Meister de Geek Squad.<br>¿ El equipo esta haciendo ruidos extraños? Si tienes suerte todo que necesitaras hacer es darle a la maquina una limpieza profunda. Las computadoras modernas tienen salvavidas que apaga el sistema si un componente esta recalentado, que puede ser la causa del frecuente reinicio cuando estas ejecutando programas de uso intensivo como los videojuegos.</h1>");
problema.push("<h2>5) PUBLICIDAD EN MI ESCRITORIO<br></h2><h1>Si no estas ejecutando tu navegador Web y todavia estas recibiendo publicidad en tu escritorio, lo mas probable es que has instalado un adware (un programa que muestra anuncios no deseados). Aunque existe adware con algunos beneficios, la mayoria de los adware no sirven de nada. No es facil deshacerse de el. <br>- Hay un monton de herramientas y utilidades de sistema que prometen limpiar de todo, con nombres como AceleraPC, PC Speed Pro, PC Speedifier,-  dice Meister de Geek Squad. - Pero la mayorias de las veces estos programas no van a hacer mucho. Algunos programas funcionan, pero otros son bastante inutiles.<br>Ejecutar un escaneo completo con software antivirus con reputacion es el primer paso. Si ese programa no encuentra y elimina el adware, prueba con Malwarebytes Anti-Malware es gratis, una gran utilidad para la eliminacion de todo tipo de malware. Solo asegurate de desactivar el software antivirus estandar antes de ejecutarlo. <br>- Multiples programas antivirus trabajando al mismo tiempo a menudo da como resultado mas problemas- , dice Petrie de Falcon Northwest. - Solo deseas tener un escaneo de antivirus a la vez, activo instalado, pero no esta de mas tener uno adicional - on demand -  que busque un virus o malware en especifico.-  <br>Buscar en linea el nombre del producto anunciado a veces puede producir resultados sobre algunos otros usuarios que han sido victimas y sabras como deshacerte de el. Si todo lo demas falla, siempre existe la opcion nuclear: vuelve a instalar el sistema completo. Tomara mucho tiempo, pero es la manera segura de quitar de raiz el adware o spyware. Recuerda que debes respaldar todos tus archivos personales.</h1>");
problema.push("<h2>6) GOOGLE NO SE VE <br></h2><h1>Los secuestradores de navegadores son un tipo bastante desagradable de malware. Tales programas asumen el papel de tu navegador Web y sigilosamente redirigen tus busquedas en Google y otras consultas a paginas falsas que tienen el firme proposito de robarte tu informacion personal o infectar tu sistema. <br>Debes ejecutar una herramienta antivirus que actue en tiempo real, esta es la mejor manera de mantenerse a salvo. Si tu navegador ya fue secuestrado, desinstala el navegador y utilizar el programa antivirus que tienes instalado en tu PC, ademas de Malwarebytes, del mismo modo que explicamos en el problema anterior, para eliminar al intruso.</h1>");
problema.push("<h2>7) MI WI-FI SE SIGUE DESCONECTANDO<br></h2><h1>Las conexiones inalambricas irregulares pueden ser un rompecabezas. ¿ Es tu computadora ? ¿ Tu router ? ¿ Su ISP ? Prueba un par de cosas antes de llamar a su proveedor de Internet. <br>Confirma que  tu computadora este dentro de la gama que cubre tu router inalambrico. Normalmente las señales debiles significan conexiones debiles. A continuacion, asegurate de que la tarjeta inalambrica de tu PC tiene los controladores mas recientes. Trata de dejar que Windows solucione los problemas por ti haciendo clic en el icono de Wi-Fi en la barra de tareas y seleccionando - solucionar problemas- .</h1>");
problema.push("<h2>8) SIGO VIENDO EL MENSAJE - HAY UN PROBLEMA CON EL CERTIFICADO DE SEGURIDAD DE ESTE SITIO WEB - <br></h2><h1>A veces los mayores problemas tienen las correcciones mas faciles. Segun los tecnicos de soporte, la mayoria de los problemas son debido a una ficha de sistema incorrecto. <br>La sincronizacion de los certificados de seguridad web debe ir de acuerdo a tu computadora. En particular las computadoras viejas corren el riesgo de tener una bateria CMOS muerta (la bateria del reloj de la computadora que mantiene el reloj de su sistema). Haz clic en el reloj en la bandeja del sistema, y selecciona Cambiar configuracion de fecha y hora para corregir cualquier problema.</h1>");
problema.push("<h2>9) MI IMPRESORA NO IMPRIME<br></h2><h1>Vamos a suponer que los controladores de la impresora estan actualizados, y que tienes suficiente papel y tinta o toner para imprimir. Prueba apagando la impresora. Desconectala y vuelve a conectarla. Comprueba que la cola de impresion de tu impresora este vacia, buscando el icono de la impresora en la bandeja del sistema y dando doble clic en el. La cola de impresion muestra el estado de cada trabajo, asi como el estado general de tu impresora. <br>Asegurate de que el - Uso de impresora Offline -  no este seleccionado. A veces, imprimir mientras tu impresora esta apagada puede causar que Windows configure tu impresora para trabajar offline, y esto puede demorar por los trabajos atrasados al configurarlo para enviados mas tarde.</h1>");
problema.push("<h2>10) NO PUEDO ABRIR LOS ARCHIVOS ADJUNTOS DE E-MAIL<br></h2><h1>Si alguna vez te pasa que tienes un archivo adjunto que no puedes abrir, probablemente es porque no tienes el software necesario para ver el archivo. <br>El sospechoso habitual es el archivo .pdf, por el cual puedes descargar un lector de PDF gratuito. Si el problema involucra un formato diferente, puedes hacer una busqueda rapida de la extension del archivo (las tres letras despues del punto, cuando termina el nombre del fichero) deberia decirte que el tipo de programa que necesita.</h1>");
problema.push("<h2>11) MI PROGRAMA FAVORITO NO FUNCIONA EN MI NUEVA PC<br></h2><h1>Antes de llamar a soporte tecnico, asegurate de que el software que estas tratando de ejecutar sea compatible con tu nuevo sistema operativo. El viejo software puede que no funcione en Windows 8, y definitivamente una aplicacion creada para Mac OS X no se ejecutara en tu PC con Windows. Un programa de 32 bits podria ejecutarse en tu sistema operativo de 64 bits, pero no funciona al reves. <br>Si un juego en linea ya no carga, te podrian faltar los plug-ins necesarios, casi siempre Java y Flash son los culpables. La mayoria de los navegadores te alertara para instalar estos programas o extensiones si es necesario.</h1>");


for(i=0 ;i<=10;i++)
{
document.write(problema[i])
}

 